### ISSUE TITLE
Fix asserts in UI tests

### ISSUE THREAD

**Issue by nonguyen1** [duchess-rs/duchess#158]
Asserts under under `duchess-java-tests/tests/ui` do not validate values.

## Reproduce

1. Checkout pkg
2. Add `assert!(false)` to any test.
3. from `duchess-java-tests` run `cargo test`

All tests should still pass.

**Comment by rcoh** [comment]
yeah, this is because of the (surprising) behavior that most of these are `//@check-pass` and not `//@run`

**Comment by rcoh** [comment]
if you're making CRs in this area, changing the tests that are `//@check-pass` to `//@run` would be welcome.

**Comment by nonguyen1** [comment]
Hehe this makes sense now haha. Sure I can update them.
