### ISSUE TITLE
Using Java reflection?

### ISSUE THREAD

**Issue by fpoli** [duchess-rs/duchess#18]
Have you considered querying class information by using Java reflection, instead of parsing the output of `javap`? Spawning a JVM in each procedural macro invocation probably has some overhead, but there would be no grammar to maintain and it would no longer be necessary to unzip JAR files to make `javap` happy.

**Comment by nikomatsakis** [comment]
I considered it. I'm open to a PR for it. I think we'll still need the grammar (or big parts of it) anyway for use in specifying which methods to codegen. I don't care about spawning up a JVM in a procedural macro -- we're doing that anyway by invoking `javap`. 

I wasn't aware of any need to unzip jar files though. 

You can't just put them on the classpath?

**Comment by fpoli** [comment]
> I wasn't aware of any need to unzip jar files though.
> 
> You can't just put them on the classpath?

I had a wrong assumption. The jar in the classpath should work fine.

**Comment by chase-ok** [comment]
One implementation note: many JVM reflection methods cause the requested class to be *initialized*. For example, [Class.forName(String)](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/Class.html#forName(java.lang.String)) notes a "call to `forName("X")` causes the class named `X` to be initialized."

[JLS 12.4](https://docs.oracle.com/javase/specs/jls/se17/html/jls-12.html#jls-12.4) goes into more detail, but the important part is class initialization triggers arbitrary code execution. All static blocks and static field initializers will be run. 

Setting aside the security concerns, the initialization code may fail in our build environment (e.g. startup code that reaches out to the network or expects certain files to be present) and prevent even trusted classes from being reflected on.

It looks like we can get around this by explicitly disabling initialization in certain calls, like [`Class.forName("X", false, null)`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/Class.html#forName(java.lang.String,boolean,java.lang.ClassLoader)), but we'll need to make sure other reflection methods we invoke don't inadvertently trigger initialization later.

**Comment by nikomatsakis** [comment]
Good call out @chase-ok; I wonder if javap does the right things to avoid that? I would assume yes, but that's probably worth verifying.

**Comment by nikomatsakis** [comment]
Going to close this for now, based on @chase-ok's point
