### ISSUE TITLE
Stability plans?

### ISSUE THREAD

**Issue by fpoli** [duchess-rs/duchess#2]
Hi :wave: I'm keeping an eye on this project because it might become a modern replacement for our [`jni-gen`](https://github.com/viperproject/prusti-dev/tree/master/jni-gen), which we wrote before procedural macros existed and is still based on `jni v0.20`.

Is `duchess` intended to (eventially) be more than just an experiment, or is it just too early to say? In the first case we'd be happy to contribute with what's missing for our use cases (e.g. access to Java fields, fast `*_unchecked` Java method calls, caching of method ids, debug assertions with runtime type checks...); in the second case we'll wait a bit more.

**Comment by nikomatsakis** [comment]
@fpoli it is intended to become a full-featured java-rust interop platform, yes, and we'd love your help in flushing it out!
