### ISSUE TITLE
Re-export `jni` and `once_cell`

### ISSUE THREAD

**Issue by fpoli** [duchess-rs/duchess#24]
Currently, clients of duchess must add `jni` and `once_cell` as dependencies ([example](https://github.com/fpoli/duchess/blob/75cfce12b6a5773679c678ef383b63cc0609ba10/test-crates/viper/Cargo.toml#L8-L9)), but there is no guarantee that tey'll use the same version that duchess uses. Re-exporting these dependencies would allow the codegen to generate `duchess::jni::` instead of `jni::` and `duchess::once_cell::` instead of `once_cell::`, so that the clients don't need to be aware of them.

**Comment by nikomatsakis** [comment]
Hmm. OK, yes, let's do that. PR, @fpoli ?

**Comment by nikomatsakis** [comment]
I don't want people to have to know about `jni` really
