### ISSUE TITLE
Ability to pass `null` to methods taking nullable parameters

### ISSUE THREAD

**Issue by chase-ok** [duchess-rs/duchess#38]
Sometimes we need to be able to pass a `null` parameter value when invoking a Java method. We already wrap Java method return values that might be `null` in a Rust `Option`, but wrapping in `Option` for all nullable parameters would litter user code with `Some()` in the common case. 

Is there a better way to use `null` values without the boilerplate? One thought is to have a special `struct JavaNull` that `impl<T: JavaObject> IntoJava<T>`, but having two different ways of representing null is confusing at best.

Or, could we add a new `trait IntoJavaObject` that abstracts over both `&T` (non-nullable) and `Option<&T>` (nullable) for `T: JavaObject`?

**Comment by nikomatsakis** [comment]
> Or, could we add a new trait IntoJavaObject that abstracts over both &T (non-nullable) and Option<&T> (nullable) for T: JavaObject?

this is what I think we should do

**Comment by nikomatsakis** [comment]
In #124 I added the ability to pass in a `duchess::Null` value that is usable wherever a java value is.
