### ISSUE TITLE
check for duplicates in interfaces

### ISSUE THREAD

**Issue by nikomatsakis** [duchess-rs/duchess#43]
@chase-ok [commented](https://github.com/duchess-rs/duchess/pull/33#discussion_r1177334226):

> If only to help catch a user making a copy/paste error, should we check the extends and implements lists have all unique elements? Ditto for method listings.

Makes sense.

**Comment by dchenbecker** [comment]
I'd like to take this one. Where should I start looking in the code?

**Comment by nikomatsakis** [comment]
@dchenbecker what you want to do is to modify the code in `check.rs` -- for example, here is the loop which checks that each of the `extends` and `implements` written by the user is actually something that appears in Java:

https://github.com/duchess-rs/duchess/blob/096ee905c7dd22e6a2fd79ed5082b5bb42d96a0b/macro/src/check.rs#L61-L78

...so we could modify that loop in a similar way.
