### ISSUE TITLE
global combinator seems redundant?

### ISSUE THREAD

**Issue by nikomatsakis** [duchess-rs/duchess#54]
Right now you write `foo.blah().global().execute()` if you want to hold on to a java object. But it would be nice if instead `execute` just gave you a global reference to begin with. (And maybe we rename global to `Java` or something like that.) 

One way to achieve this: rename `JvmOp::Output` to `JvmOp::LocalOutput` and add a `GlobalOutput`. 

The other obvious thing would be to have some kind of `IntoGlobal` trait which is implemented by most things. The challenge would be that we also (at least with current design) have to implement it for Rust types that may be output from `ToRust`. But that's doable, I suppose, there's not an infinite set of Rust types that can emerge from there.

**Comment by nikomatsakis** [comment]
### Mentoring instructions (Option A)

Here is how I think I would do it.

The `IntoGlobal` trait already exists...

https://github.com/duchess-rs/duchess/blob/dde8a04b923fd2f7cb6aa7f1f74dcf40596f44ae/src/global.rs#L37-L41

...but it's [only implemented for java references](https://github.com/duchess-rs/duchess/blob/dde8a04b923fd2f7cb6aa7f1f74dcf40596f44ae/src/global.rs#L43-L74). I would...

* implement it for [the java scalars](https://github.com/duchess-rs/duchess/blob/dde8a04b923fd2f7cb6aa7f1f74dcf40596f44ae/src/jvm.rs#L378-L387)
* modify the [`ToRust` derive](https://github.com/duchess-rs/duchess/blob/dde8a04b923fd2f7cb6aa7f1f74dcf40596f44ae/macro/src/derive.rs#L20-L32) so that it also produces a `impl IntoGlobal` for the output type that just does an identity conversion (i.e.,  `fn into_global(self, jvm: &mut Jvm<'jvm>) -> crate::Result<'jvm, Self::Output>` returns `Ok(self)`).
* modify the [`execute`](https://github.com/duchess-rs/duchess/blob/dde8a04b923fd2f7cb6aa7f1f74dcf40596f44ae/src/jvm.rs#L99-L104) method of `JvmOp` to require that `for<'jvm> Self::Output<'jvm>: IntoGlobal<Output = R>` and of invoke `into_global` on the return value.

**Comment by nikomatsakis** [comment]
Once that is done, you can go in the codebase and remove calls to `global` (maybe remove the `global` combinator? but it doesn't hurt) and check that it works.

**Comment by nikomatsakis** [comment]
I started working on this in my `no-more-global` branch -- it's not as easy as I thought, of course. The instructions more-or-less worked but it causes type inference errors that seem very painful, and i'm not sure yet if there's a good way to deal with them. 

Quick to-do list for myself:

* [x] Basic idea
* [ ] Fix type inference errors
* [ ] Make `IntoGlobal` trait unsafe and add some kind of transmute hack to avoid expensive clones

**Comment by rcoh** [comment]
This was fixed by #147
