### ISSUE TITLE
jvm builder

### ISSUE THREAD

**Issue by nikomatsakis** [duchess-rs/duchess#6]
The [`Jvm`](https://github.com/nikomatsakis/duchess/blob/0a1dd1ec20bbe8aee52077ef149f6019a99a5108/src/jvm.rs#L63-L66) type is kind of a placeholder. The [docs](https://github.com/nikomatsakis/duchess/blob/main/book/src/jvm.md) describe how it should look eventually, e.g., with a builder that lets you set the classpath and other important options.

**Comment by nikomatsakis** [comment]
See also @fpoli's comments here https://github.com/duchess-rs/duchess/pull/45#discussion_r1180341027

**Comment by fpoli** [comment]
(I rephrase here my comments.)

Reading the ["Starting multiple JVMs"](https://duchess-rs.github.io/duchess/jvm.html#starting-multiple-jvms) section of the current documentation I got the (wrong) impression that sequential `Jvm::with(|jvm|..)`  calls are meant in the long term to start and stop multiple JVMs. However, via JNI one can only start at most one JVM for the full the *lifetime* of a process ([source](https://bugs.openjdk.org/browse/JDK-4712793)). That is, trying to start a second JVM after destroing one will always fail.

Re-reading the documentation with a fresh mind, I now see that the "multiple JVMs" of the documentation actually refers to multiple instances of the `Jvm` struct. PR https://github.com/duchess-rs/duchess/pull/47 should avoid any further confusion.

My suggestion of [`std::sync::OnceLock`](https://doc.rust-lang.org/nightly/std/sync/struct.OnceLock.html) is still valid; it's a concurrent `OnceCell`. That type makes it possible to initialize a global JVM with user-provided arguments.
